title: 
email: 
description: 
baseurl: 
url: https://
author: 
twitter: 
github: 
logo: /logo.png

markdown: kramdown

plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-avatar

sass:
  style: compressed
  sourcemap: always
